language: python
python:
   - "3.6"
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "OKdJ4MPU6k7anmIWwenkFls4AU22FFUpgOMsIrpdgmpc2JCbpiZ/OOR0dAP4ocOY2JggQr8hgc7D5b+HfnJKWng5SE/L9uI70PX9vjkxwc57VKTXEnCtRJV7MJv0g74axIyYvppyCzEaQDmBZJW1pRXRm6carGpV8gPncttm8ylPlu7Sy/JuQqxF2J10HYyDcUBYM6dhSX6Ecwzr/lSz4+pXL5TPW++ALKCF6eWIzA7QQmLW8VrOJfUuO+T3fqyRb8PItOZ8XmQF2jHsWtuNSLVP0i9ZHxKrsYsP162QnXdBMdbzQTbjcxtg9ImNkfcmUljDoCcoWV35X9HU1sEQfLTu1P8Evx4RwlaEkoWTsDEV8xvRq6gYM0Yoo63sIvyXJE7IhnGHLdR5yOUWnaNTdTMjIgCWtGEKcJHihPW+XJpu5d3iYBKgsMlLm1EpUia4QO2cVrJgq9feil3Wqd/ScFCOKmmMe1r610cq8VE17eJFYXssrPnUdaF70qglC3KWpzTvGPoN6O+f4C7Ydf5RtaVSF1c4seYHFE3hHu7A4XCIhdELuHxudk5+dLsJesIBFL5H4XoirLYXcNEVRM4thJMdJ1zK61KBXmZHkdeaPikVDhylYK2PdDPeAJV1Pq2lFHAw2B8Kh5o6FLPQ71cxulOuCOcUNIN1JsE8vw5vjrE="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "malloblenne/guardian"
      description: "Build submitted via Travis CI"
    notification_email: malloblenne@gmail.com
    build_command_prepend: ""
    build_command:   ""
    branch_pattern:  coverity-travis

install: "pip install -r requirements.txt"
script: pytest