language: python
python:
   - "3.6"
env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "cjiNUgge/rQcCnQc0gIALHPfQ7DVCkiQ0ZckW/cCS9VpzeA1EUrtRC+XRvfZ+Kvi4FjrbtqPmosg7RToyqqHz/WBG91rIaZKdovtrxB3l5XoS/pyptoqqZMF9GQTMtWVRd9vLyJb4nP7NPiG9XRDnWwJ1Q8i6AYDeN6wpYyrxwO/MmeUKNXj8bd0cdEdQT30PXF+YR+5L/hWVa8FJnOCJZbnmyC+KsN7z09a67myKBxY0kUw0Xo421yEth5l+4MyhsRbT+Ud/sQQit0bkI94nPsFxrwXLn6yLVcJneVFpBnfenfnRbpVXobfkr72zv3zc04ahL4lpJr2k5atgI26DZ+DcvJf9Zmi/7MBwkGe+z8ZxKNTRx3xC0Op1+SKHTzREy4dqH/b2g27Q0Q5TQALG76KIUIwf14vQTYivqFMCu7DkDdwpL8cR+XEQ/yAg1YgBZEJ+mq1+Aig4qbobKGUDwJs/XjhfSES/xvAl+Oe9bvPI6R4qJp8c2BNhOTbdFHS+39dUw8CyPQyDXznyemCXtJ+rkiSrsauG6gnxgb36B3aaHYOlnRut9McjDkUA3HS1ec+ho5Dil5Mq4m2BqQv43ozHMgm7ir5zcg0SmfVFcalDFKNeG8YcuRo4LwO3FXvmuRMGx5VsMp83i+C9NJSaFO3tRTRtXCNwQ9iNmv6fUk="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "malloblenne/guardian"
      description: "Build submitted via Travis CI"
    notification_email: malloblenne@gmail.com
    build_command_prepend: ""
    build_command:   ""
    branch_pattern: coverity_scan